### ISSUE TITLE
Vue.js missing from client-side side-by-side benchmark comparison

### ISSUE THREAD

**Issue by danrichman** [marko-js/isomorphic-ui-benchmarks#3] opened 2017-03-04 00:11 UTC
If you run client-side benchmarks, vue.js is missing from the results and vue.js does not render as a comparison in the page. Although, vue.js does render as an individual client-side benchmarks page.

**Comment by danrichman** [comment] 2017-03-04 00:12
Also, vue.js is missing from the published output results listed on this repo's github documentation. That should be updated.

**Comment by danrichman** [comment] 2017-03-04 00:14
And while you're in the github documentation, the listed command to run server-side benchmarks is incorrect. It's currently listed as:

```
npm run benchmarks
```

But it should be singular, not plural. As in.


```
npm run benchmark
```

**Comment by patrick-steele-idem** [comment] 2017-03-04 15:33
A new version of an in-range dependency seem to have broken the Vue build (not sure if the problem is with Vue or Rollup or something else). I'll take a look when I get a chance, but for right now the server-side benchmarks still run with Vue and the client-side benchmarks do not include Vue. I'll take a look when I get a chance. Thanks for reporting the problem.

**Comment by DylanPiercey** [comment] 2019-10-22 00:26
Fixed now, sorry it took forever!

**Closed by DylanPiercey** 2019-10-22 00:26 UTC
